[postgres]
version = 18

[[instances]]
cluster_name = "main1"
port = 5432
admin_user = "pgadmin1"
socket_dir = "/var/run/postgresql"

[[instances]]
cluster_name = "main2"
port = 5433
admin_user = "pgadmin2"
socket_dir = "/var/run/postgresql"

[database]
name = "demodb"

[table]
name = "demo"
